apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
  namespace: argocd
  labels:
    app: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      containers:
        - name: flask-container
          image: dipchand20/flask-hello-world:v0.1.1
          ports:
            - containerPort: 5000
      imagePullSecrets:
        - name: dockerhub-secret1